development:
  adapter: postgis
  database: spek_dev
  host: localhost
  pool: 5
  timeout: 5000
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'

test:
  adapter: postgis
  database: spek_test
  host: localhost
  pool: 5
  timeout: 5000
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'

# THIS IS REPLACED ON HEROKU DEPLOY
production:
  adapter: postgis
  database: spek_production
  host: localhost
  pool: 5
  timeout: 5000
  postgis_extension: postgis
  schema_search_path: '"$user", public, postgis'