development:
  adapter: postgresql
  database: spek_dev
  host: localhost
  pool: 16
  timeout: 5000
  postgis_extension: postgis

test:
  adapter: postgresql
  database: spek_test
  host: localhost
  pool: 16
  timeout: 5000
  postgis_extension: postgis

# THIS IS REPLACED ON HEROKU DEPLOY
production:
  adapter: postgis
  database: spek_production
  host: localhost
  pool: 16
  timeout: 5000
  postgis_extension: postgis