development:
  adapter: postgresql
  database: spek_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: spek_test
  host: localhost
  pool: 5
  timeout: 5000

# THIS IS REPLACED ON HEROKU DEPLOY
production:
  adapter: postgresql
  database: spek_production
  host: localhost
  pool: 5
  timeout: 5000